name: 'Validate CODEOWNERS'
description: 'GitHub Action to validate CODEOWNERS in the repository'
inputs:
  checks:
    description: 'Select the checks to run (leave empty to run all checks)'
    required: false
    default: ''
    type: 'string'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ contains(inputs.checks, 'check_exists') && '--check-exists' || '' }}
    - ${{ contains(inputs.checks, 'duplicate_patterns') && '--duplicate-patterns' || '' }}
    - ${{ inputs.checks == '' && '--all' || '' }}
branding:
  icon: 'shield'
  color: 'orange'
