name: 'Validate CODEOWNERS'
description: 'GitHub Action to validate CODEOWNERS in the repository'

inputs:
  checks:
    description: 'Comma-separated list of checks to run. Options: exists, duplicate_patterns. Default: all.'
    required: false
    default: 'all'
    type: string

runs:
  using: 'docker'
  image: 'docker://ghcr.io/ryan-flan/codeowners-validation:v0.4.3'
  args:
    - ${{ inputs.checks }}

branding:
  icon: 'shield'
  color: 'orange'

