name: 'Validate CODEOWNERS'
description: 'GitHub Action to validate CODEOWNERS in the repository'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/ryan-flan/codeowners-validation:v0.1.1'
branding:
  icon: 'shield'
  color: 'orange'
