name: 'Validate CODEOWNERS'
description: 'GitHub Action to validate CODEOWNERS in the repository'

inputs:
  checks:
    description: 'Select the checks to run (comma-separated)'
    required: false
    default: 'all'
    type: string

runs:
  using: 'docker'
  image: 'docker://ghcr.io/ryan-flan/codeowners-validation:v0.4.2'
  args:
    - ${{ inputs.checks }}

branding:
  icon: 'shield'
  color: 'orange'

