name: 'Validate CODEOWNERS'
description: 'GitHub Action to validate CODEOWNERS in the repository'
inputs:
  checks:
    description: 'Select the checks to run (comma-separated)'
    required: false
    default: 'all'
    type: string

runs:
  using: 'composite'
  steps:
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Cache Cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/
        key: cargo-cache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-cache-${{ runner.os }}-

    - name: Install CODEOWNERS Validation (if needed)
      id: install
      run: |
        if ! command -v codeowners-validation > /dev/null; then
          cargo install codeowners-validation
        fi
      shell: bash

    - name: Run CODEOWNERS Validation
      run: codeowners-validation "${{ inputs.checks }}"
      env:
        CARGO_TERM_COLOR: always
      shell: bash

branding:
  icon: 'shield'
  color: 'orange'

