[package]
name = "codeowners-validation"
version = "0.1.1"
edition = "2021"

[dependencies]
glob = "0.3"
walkdir = "2"
globset = "0.4"
clap = {version = "4.5.4", features = ["derive"]}

[dev-dependencies]
tempfile = "3.2.0"
