name: Validate CODEOWNERS

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CODEOWNERS validation 
        uses: ryanjamesflanagan/codeowners-validation@v0.2.1
        with:
          checks: |
            "exists"
            "duplicate_patterns"
